### ISSUE TITLE
console.log

### ISSUE THREAD

**Issue by slik** [kassens/frameworks#3]
Hi.

Tried to update before posting this, but nothing changed.

Just you forgot to remove console.log call:

> chrome-extension://jggheggpdocamneaacmfoipeehedigia/redux/contentscript.js:88

**Comment by kassens** [comment]
I think another plugin is causing the error, since the content script of this plugin is called `content_script.js` not `contentscript.js` and I can't find a console statement anywhere.

**Comment by slik** [comment]
Sorry then, my bad.
